### ISSUE TITLE
Error persists with Elgamal encryption decryption. 

### ISSUE THREAD

**Issue by JoeltheSpider** [JoeltheSpider/RIE-RID#1]
I have a separate module for integer elgamal op in ./reference .
It works fine, but when the same algo is put to images, image is not recovered.
Please _look into this issue_ @GHub4Rashmi.

**Comment by GHub4Rashmi** [comment]
Hey @JoeltheSpider , the error is resolved. After encryption, when you save the image, pixel values will be saved below 255. So, the encrypted values will be modified. Instead of saving it as an image, store it as a matrix.
